"""Allow multiple developers per user

Revision ID: d4735f6ed920
Revises: 3438ee26fd94
Create Date: 2026-10-08 09:27:35.395764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4735f6ed920'
down_revision = '3438ee26fd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    op.create_table('developers',
        sa.Column('id', sa.String(length=24), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    conn.execute(sa.text("""
        INSERT INTO developers(id)
        SELECT pebble_dev_portal_uid
        FROM users;
    """))
    op.create_table('user_developer',
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('developer_id', sa.String(length=24), nullable=True),
        sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ondelete='cascade'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade')
    )
    conn.execute(sa.text("""
        INSERT INTO user_developer(user_id, developer_id)
        SELECT id, pebble_dev_portal_uid
        FROM users;
    """))
    op.drop_column('users', 'pebble_dev_portal_uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    op.add_column('users', sa.Column('pebble_dev_portal_uid', sa.VARCHAR(length=24), autoincrement=False, nullable=True))
    conn.execute(sa.text("""
        UPDATE users u
        SET    pebble_dev_portal_uid = d.developer_id
        FROM   user_developer d
        WHERE  u.id = d.user_id
    """))
    op.drop_table('user_developer')
    op.drop_table('developers')
    # ### end Alembic commands ###
