"""Create groups

Revision ID: eced49e24f25
Revises: 3438ee26fd94
Create Date: 2026-10-07 23:28:22.899758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eced49e24f25'
down_revision = '3438ee26fd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    op.create_table('groups',
        sa.Column('id', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    conn.execute(sa.text("""
        INSERT INTO groups(id)
        VALUES ('wizard');
    """))
    op.create_table('group_users',
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('group_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='cascade'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade')
    )
    conn.execute(sa.text("""
        INSERT INTO group_users(user_id, group_id)
        SELECT id, 'wizard'
        FROM users
        WHERE is_wizard = 'true';
    """))
    op.drop_column('users', 'is_wizard')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    op.add_column('users', sa.Column('is_wizard', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    conn.execute(sa.text("""
        UPDATE users u
        SET    is_wizard = 'true'
        FROM   group_users g
        WHERE  u.id = g.user_id
    """))
    op.drop_table('group_users')
    op.drop_table('groups')
    # ### end Alembic commands ###
